# Tarpaulin Code Coverage Configuration for Cap'n Web Rust

[default]
# Coverage options
exclude-files = ["*/tests/*", "*/benches/*", "*/examples/*", "*/.cargo/*"]
ignored = ["capnweb-interop-tests"]
timeout = "600s"
debug = false
all-features = true
workspace = true
avoid-cfg-tarpaulin = true

# Output formats
out = ["Html", "Xml", "Lcov"]
output-dir = "target/coverage"

# Coverage thresholds
fail-under = 0  # We'll check current coverage first
print-summary = true
print-uncovered-lines = true

[report]
skip-clean = false
